version: "2"
services:
  app:
    container_name: fast
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - 80:80
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 5432:5432
    expose:
      # Opens port 3306 on the container
      - 5432
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

  pgadmin:
    image: biarms/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050