version: "2"
services:
  app:
    container_name: fast
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - 80:80
    depends_on:
      - DB
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      FILEBASE_KEY: ${FILEBASE_KEY}
      FILEBASE_SECRET: ${FILEBASE_SECRET}
  DB:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf