name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/Dockerfile
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rasp-fast-app-image:latest
  pull:
    needs: build
    runs-on: self-hosted
    steps:
      - 
        name: Stop container & Remove Container
        run: |
          docker stop fast
          docker rm fast
      - 
        name: Pull latest image
        run: docker pull quentin973/rasp-fast-app-image:latest
      - 
        name : Create new container
        run: docker run -d --name fast -p 80:80 quentin973/rasp-fast-app-image:latest
