name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Backend Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:app"
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rasp-fast-app-image:latest

      - 
        name: Frontend Build and Push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          secrets: |
            "REACT_APP_API_HOST=${{ secrets.REACT_APP_API_HOST}}"

  pull:
    needs: build
    runs-on: self-hosted
    steps:
      - 
        name: Stop container & Remove Container
        run: |
          docker stop fast
          docker rm fast

      - 
        name: Fast API Pull latest image
        run: docker pull quentin973/rasp-fast-app-image:latest
  
      - 
        name : Create new container
        run: docker run --env-file .env -d --restart unless-stopped  --name fast -p 8000:8000 quentin973/rasp-fast-app-image:latest

      - 
        name: Frontend Stop container & Remove Container
        run: |
          docker stop react
          docker rm react

      - 
        name: Frontend Pull latest image
        run: docker pull quentin973/frontend:latest

      - 
        name: Frontend Create new container
        run: docker run --name react -p 80:80  quentin973/frontend