name: ci

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Backend Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:app"
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rasp-fast-app-image:latest


  pull:
    needs: build
    runs-on: self-hosted
    steps:
      - 
        name: Stop container & Remove Container
        run: |
          docker stop fast
          docker rm fast
        continue-on-error: true

      - 
        name: Fast API Pull latest image
        run: docker pull quentin973/rasp-fast-app-image:latest

      - 
        name: Print current directory
        run: pwd
  
      - 
        name : Create new container
        run:  cd Work/FastAPI && docker run --env-file .env -d --restart unless-stopped  --name fast -p 8000:8000 quentin973/rasp-fast-app-image:latest

      - 
        name : Build Frontend
        run: cd Work/FastAPI/frontend && sudo npm run build

